name: Java CI with Maven

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Диагностика Docker
      - name: Check Docker Status
        run: |
          sudo systemctl status docker || echo "Docker is not running!"

      - name: Ensure Docker Group Membership
        run: |
          sudo groupadd docker || true
          sudo gpasswd -a $USER docker
          sudo chown "$USER:$USER" /home/"$USER"/.docker -R
          sudo chmod g+rwx "/home/$USER/.docker" -R

      - name: Restart Docker Service
        run: |
          sudo systemctl restart docker

      - name: Check Docker Socket Accessibility
        run: |
          ls -l /var/run/docker.sock
          if [[ ! -S /var/run/docker.sock ]]; then
              echo "Docker socket does not exist or is not a valid UNIX domain socket."
              exit 1
          fi

      - name: Check Docker Connection
        run: |
          curl --unix-socket /var/run/docker.sock http:/info || echo "Docker connection failed!"

      - name: Clean Docker Images
        run: |
          docker rmi $(docker images -q) || true

      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        env:
          DOCKER_HOST: unix:///var/run/docker.sock
          TESTCONTAINERS_RYUK_DISABLED: "true"
          DOCKER_CLIENT_VERSION: "1.44"
        run: mvn -B clean verify --file pom.xml
